module.exports = [
  {
    school: 'acf',
    emoji: '🎭',
    name: 'SMU Eurhythmix',
    meta: 'ACF · DANCE · A CAPPELLA',
    desc: 'Audition-based dance crew bringing K-pop, hip-hop and contemporary to every campus stage worth standing on.',
    badge: 'hot',
    badgeText: '★ Auditioning',
  },
  {
    school: 'acf',
    emoji: '🎼',
    name: 'Voix Concordia',
    meta: 'ACF · CHOIR',
    desc: "SMU's 60-strong mixed choir. Annual concert at Esplanade. Sight-reading helps but isn't required.",
    badge: 'open',
    badgeText: 'Open',
  },
  {
    school: 'sics',
    emoji: '🌍',
    name: 'SMU Eco',
    meta: 'SICS · ENVIRONMENT',
    desc: 'Sustainability club running campus audits, beach cleans and the Vivace zero-waste pop-up market.',
    badge: 'new',
    badgeText: '★ New',
  },
  {
    school: 'sics',
    emoji: '🐶',
    name: 'Project Pawprint',
    meta: 'SICS · COMMUNITY SERVICE',
    desc: 'Volunteers with shelters across Singapore. Weekly walks, monthly adoption drives, regular merch sales.',
    badge: 'open',
    badgeText: 'Open',
  },
  {
    school: 'icon',
    emoji: '🌏',
    name: 'SMU ASEAN',
    meta: 'ICON · INTERNATIONAL',
    desc: 'Cross-cultural exchange across SE Asia. Hosts the annual SMU-ASEAN Forum and overseas study trips.',
    badge: 'open',
    badgeText: 'Open',
  },
  {
    school: 'smux',
    emoji: '🏀',
    name: 'SMU Basketball',
    meta: 'SMUX · SPORTS',
    desc: "Men's and women's varsity teams. IVP champions 3 years running. Try-outs Aug 14, no walk-ins.",
    badge: 'hot',
    badgeText: '★ Try-outs',
  },
  {
    school: 'smux',
    emoji: '🏓',
    name: 'SMU Table Tennis',
    meta: 'SMUX · SPORTS',
    desc: 'From total beginners to ex-national paddlers. Weekly socials + competitive squad.',
    badge: 'open',
    badgeText: 'Open',
  },
  {
    school: 'ssu',
    emoji: '🎤',
    name: "Patron's Voice",
    meta: 'SSU · STUDENT VOICE',
    desc: 'Student feedback channel — runs town halls, surveys, and the Vivace 2026 organising committee itself.',
    badge: 'open',
    badgeText: 'Open',
  },
  {
    school: 'gri',
    emoji: '📈',
    name: 'SMU Investment Society',
    meta: 'GRI · FINANCE',
    desc: 'Equity research, stock pitches, alumni mentorship. Application-based with two recruitment rounds per semester.',
    badge: 'hot',
    badgeText: '★ Recruiting',
  },
  {
    school: 'gri',
    emoji: '💼',
    name: 'Consult & Co.',
    meta: 'GRI · STRATEGY',
    desc: 'Pro-bono consulting club for non-profits and SMEs. Casing weekly, real engagements every term.',
    badge: 'open',
    badgeText: 'Open',
  },
  {
    school: 'acad',
    emoji: '📚',
    name: 'SMU Lex Society',
    meta: 'ACADEMIC · LAW',
    desc: 'Law student body — moots, mock trials, big-firm career nights, the works.',
    badge: 'open',
    badgeText: 'Open',
  },
  {
    school: 'acad',
    emoji: '💻',
    name: 'SCIS.club',
    meta: 'ACADEMIC · COMP. SCI.',
    desc: "Hackathons, tech-talk Fridays, alumni Q&As. Open to all majors who want to write code without judgement.",
    badge: 'new',
    badgeText: '★ New',
  },
];
