module.exports = [
  {
    picClass: 'p1',
    day: '11',
    dayLabel: 'AUG · MON',
    wordmark: 'OPENING',
    title: 'Opening Day Showcase',
    time: '10:00 — 14:00',
    venue: 'SMU Concourse, L1',
    desc: 'Ribbon-cutting, school umbrella parade, free Vivace tote for first 500 attendees.',
    admission: 'Free entry',
  },
  {
    picClass: 'p2',
    day: '12',
    dayLabel: 'AUG · TUE',
    wordmark: 'TRY-OUTS',
    title: 'CCA Try-out Night',
    time: '17:00 — 21:00',
    venue: 'SOA Gym + Studios',
    desc: 'Six sports, four dance crews, one shot at making the team. Pre-booking recommended via the Explore page.',
    admission: 'Pre-book',
  },
  {
    picClass: 'p3',
    day: '13',
    dayLabel: 'AUG · WED',
    wordmark: 'FINALE',
    title: 'Closing Performance',
    time: '18:30 — 21:00',
    venue: 'SMUC Hall',
    desc: "The night every CCA shows off what they've been rehearsing all year. Ticketed, doors at 18:00.",
    admission: 'Ticketed',
  },
];
