module.exports = {
  sponsors: [
    { name: '7-Eleven', tileClass: 't1' },
    { name: 'FairPrice', tileClass: 't2' },
    { name: 'Koi Thé', tileClass: 't3' },
    { name: 'PUMA', tileClass: 't4' },
    { name: 'Grab', tileClass: 't5' },
    { name: 'Ya Kun', tileClass: 't6' },
  ],
  deals: [
    {
      headStyle: '',
      percStyle: '',
      perc: '15%',
      title: 'OFF YOUR FIRST RUN',
      who: 'Grab Food · Vivace Code: VIVACE15',
      whoStyle: '',
      body: 'First-time SMU students get 15% off any Grab Food order over $10. Valid through August.',
      validity: 'Valid 11 — 31 Aug 2026',
      cta: 'Redeem →',
    },
    {
      headStyle: 'background:var(--pink); color:#fff',
      percStyle: 'color:#fff',
      perc: '1+1',
      title: 'BUY ONE GET ONE',
      who: 'Koi Thé · Bras Basah outlet',
      whoStyle: 'color:rgba(255,255,255,.85)',
      body: 'Bring a friend. Buy any signature milk tea, get the second one on the house.',
      validity: 'Valid event days only',
      cta: 'Redeem →',
    },
    {
      headStyle: 'background:var(--green); color:#fff',
      percStyle: 'color:#fff',
      perc: 'FREE',
      title: 'VIVACE TOTE BAG',
      who: 'FairPrice · while stock lasts',
      whoStyle: 'color:rgba(255,255,255,.85)',
      body: 'First 500 attendees take home a limited-edition Vivace x FairPrice canvas tote.',
      validity: 'While stock lasts',
      cta: 'Claim →',
    },
  ],
};
